from datetime import datetime, timedelta
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from jose import JWTError, jwt
from passlib.context import CryptContext
from pydantic import BaseModel
from sqlalchemy.orm import Session
from sqlalchemy.util import deprecated
from starlette import status

from database import SessionLocal
from dependency import db_dependency
from models import Users

router = APIRouter(prefix="/auth", tags=["auth"])
# SECRET_KEY Can be generated by "openssl rand -hex 32" command.
SECRET_KEY = "eb678b8c1126ba9137438e45a0d16fe4bd2eb03474854e59c3bd7b25b9a4be77" 
ALGORITHM = "HS256"

#We use bcrypt to securely hash user passwords:
bcrypt_context = CryptContext(schemes=["bcrypt"], deprecated="auto", bcrypt__rounds=12)
oauth2_bearer = OAuth2PasswordBearer(tokenUrl="auth/token")


class CreateUserRequest(BaseModel):
    username: str
    password: str


class Token(BaseModel):
    access_token: str
    token_type: str


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@router.post("/", status_code=status.HTTP_201_CREATED)
async def create_user(db: db_dependency, create_user_request: CreateUserRequest):
    """
    Creates a new user with a hashed password and stores it in the database.
    """
    # Validate password length
    if len(create_user_request.password) > 72:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Password cannot be longer than 72 characters"
        )
    
    if len(create_user_request.password) < 6:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Password must be at least 6 characters long"
        )
    
    # Check if user already exists
    existing_user = db.query(Users).filter(Users.username == create_user_request.username).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username already exists"
        )
    
    # Handle password length for bcrypt (72 byte limit)
    original_password = create_user_request.password
    
    # Convert to bytes to check actual byte length
    password_bytes = original_password.encode('utf-8')
    
    if len(password_bytes) > 72:
        # Truncate to 72 bytes, then decode back to string
        truncated_password = password_bytes[:72].decode('utf-8', errors='ignore')
    else:
        truncated_password = original_password
    
    # Use the truncated password for hashing
    hashed_password = bcrypt_context.hash(truncated_password)
    
    create_user_model = Users(
        username=create_user_request.username,
        hashed_password=hashed_password,
    )
    db.add(create_user_model)
    db.commit()
    
    return {"message": "User created successfully", "username": create_user_request.username}


def authenticate_user(username: str, password: str, db):
    """
    Verifies the username and password against stored hashed password.
    Returns the user if authentication is successful, otherwise returns False.
    """
    user = db.query(Users).filter(Users.username == username).first()
    if not user:
        return False
    
    # Handle password length for bcrypt (72 byte limit)
    password_bytes = password.encode('utf-8')
    if len(password_bytes) > 72:
        # Truncate to 72 bytes, then decode back to string
        truncated_password = password_bytes[:72].decode('utf-8', errors='ignore')
    else:
        truncated_password = password
    
    try:
        if not bcrypt_context.verify(truncated_password, user.hashed_password):
            return False
        return user
    except Exception as e:
        print(f"Password verification error: {e}")
        # If there's a hash format error, the user needs to reset their password
        return False


def create_access_token(username: str, user_id: int, expires_delta: timedelta):
    """
    Generates a JWT access token with an expiration time.
    """
    encode = {"sub": username, "id": user_id}
    expires = datetime.utcnow() + expires_delta
    encode.update({"exp": expires})
    return jwt.encode(encode, SECRET_KEY, algorithm=ALGORITHM)


def get_current_user(token: Annotated[str, Depends(oauth2_bearer)]):
    """
    Decodes the JWT token and retrieves user details.
    Raises an exception if the token is invalid or expired.
    """
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        user_id: str = payload.get("id")
        if username is None or user_id is None:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Could not validate user",
            )

        return {"username": username, "id": user_id}

    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED, detail="Could not validate user"
        )


@router.post("/token", response_model=Token)
async def login_for_access_token(
    form_data: Annotated[OAuth2PasswordRequestForm, Depends()], db: db_dependency
):
    """
    Authenticates user credentials and returns a JWT token if valid.
    """
    user = authenticate_user(form_data.username, form_data.password, db)

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED, detail="Could not validate User"
        )
    username = user.username
    user_id = user.id
    token = create_access_token(username, user_id, timedelta(minutes=20))

    return {"access_token": token, "token_type": "bearer"}